name: Testing
on: push

jobs:
  test_project:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Install pipenv
    run: 
      python -m pip install --upgrade pipenv

  - name: Install dependencies
    run: 
      pipenv install --dev

  - name: Run Django unit tests
    run:
      python3 manage.py test