# Generated by Django 4.1.5 on 2023-01-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=255, null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('story_id', models.IntegerField()),
                ('kids', models.JSONField(default=dict, verbose_name='children')),
                ('score', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=2064)),
                ('dead', models.BooleanField(null=True)),
                ('url', models.URLField(max_length=255, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_types', to='newsappAPI.type')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_option_id', models.IntegerField(null=True)),
                ('by', models.CharField(max_length=255, null=True)),
                ('deleted', models.BooleanField(null=True)),
                ('kids', models.JSONField(default=dict, verbose_name='children')),
                ('parent', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=2064)),
                ('time', models.IntegerField(null=True)),
                ('dead', models.BooleanField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_option_types', to='newsappAPI.type')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.IntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('by', models.CharField(max_length=255, null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('kids', models.JSONField(default=dict, verbose_name='children')),
                ('score', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('dead', models.BooleanField(null=True)),
                ('deleted', models.BooleanField(null=True)),
                ('text', models.CharField(max_length=2064)),
                ('url', models.URLField(max_length=255, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll_types', to='newsappAPI.type')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('by', models.CharField(max_length=255, null=True)),
                ('kids', models.JSONField(default=dict, verbose_name='children')),
                ('text', models.CharField(max_length=2064)),
                ('time', models.IntegerField(null=True)),
                ('dead', models.BooleanField(null=True)),
                ('deleted', models.BooleanField(null=True)),
                ('url', models.URLField(max_length=255, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_types', to='newsappAPI.type')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('deleted', models.BooleanField(null=True)),
                ('by', models.CharField(max_length=255, null=True)),
                ('time', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=2064)),
                ('dead', models.BooleanField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('kids', models.JSONField(default=dict, verbose_name='children')),
                ('url', models.URLField(max_length=255, null=True)),
                ('score', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('poll', models.IntegerField(null=True)),
                ('parts', models.JSONField(default=dict, verbose_name='parts')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='newsappAPI.type')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(null=True)),
                ('by', models.CharField(max_length=255, null=True)),
                ('kids', models.JSONField(default=dict, verbose_name='children')),
                ('parent', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=2064)),
                ('time', models.IntegerField(null=True)),
                ('dead', models.BooleanField(null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='newsappAPI.story')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_types', to='newsappAPI.type')),
            ],
        ),
    ]
