# Generated by Django 4.1.5 on 2023-01-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
    ]
