# Generated by Django 4.1.5 on 2023-01-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0002_remove_item_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parts',
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=2064, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='newsappAPI.type'),
        ),
    ]
