# Generated by Django 4.1.5 on 2023-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0003_remove_item_parts_alter_item_text_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parts',
            field=models.JSONField(default=dict, verbose_name='parts'),
        ),
    ]
