# Generated by Django 4.1.5 on 2023-01-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0006_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
