# Generated by Django 4.1.5 on 2023-01-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0007_alter_item_deleted_alter_item_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(default='HN', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='kids',
            field=models.JSONField(default=dict, verbose_name='kids'),
        ),
    ]
