# Generated by Django 4.1.5 on 2023-01-10 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0008_item_source_alter_item_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='by',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='descendants',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='poll',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_id', models.IntegerField(null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=128)),
                ('by', models.CharField(blank=True, max_length=255)),
                ('time', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('dead', models.BooleanField(default=False)),
                ('parent', models.IntegerField(blank=True)),
                ('kids', models.JSONField(default=dict, verbose_name='kids')),
                ('url', models.URLField(max_length=255, null=True)),
                ('score', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('descendants', models.IntegerField(blank=True)),
                ('poll', models.IntegerField(null=True)),
                ('parts', models.JSONField(default=dict, verbose_name='parts')),
                ('source', models.CharField(default='HN', max_length=255)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='newsappAPI.item')),
            ],
        ),
    ]
