# Generated by Django 4.1.5 on 2023-01-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0009_alter_item_by_alter_item_dead_alter_item_descendants_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kids',
            new_name='Kid',
        ),
    ]
