# Generated by Django 4.1.5 on 2023-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0011_remove_kid_descendants_remove_kid_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='descendants',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kid',
            name='parts',
            field=models.JSONField(default=dict, verbose_name='parts'),
        ),
        migrations.AddField(
            model_name='kid',
            name='poll',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kid',
            name='score',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
