# Generated by Django 4.1.5 on 2023-01-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0015_alter_kid_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descendants',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kid',
            name='by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kid',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kid',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
