# Generated by Django 4.1.5 on 2023-01-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsappAPI', '0016_alter_item_descendants_alter_item_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='kid_id',
            field=models.IntegerField(null=True),
        ),
    ]
